name: accra_transit_optimizer
description: AI-powered public transport optimization for Accra.

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_map: ^6.0.1
  latlong2: ^0.9.1
  provider: ^6.1.1
  geolocator: ^10.1.0
  permission_handler: ^11.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
